import { promises as fs } from "fs";
import path from "path";
import { randomUUID } from "crypto";

// Local filesystem backend for the universal media system. Files live OUTSIDE the
// public dir (a private `uploads/media` folder) and are only ever served through
// the auth-scoped GET /api/media/[id] route — never as public static assets. The
// storage key is `<userId>/<uuid>.<ext>`, generated by us, so nothing user-supplied
// ever reaches the filesystem path (no traversal).
const MEDIA_ROOT = path.join(process.cwd(), "uploads", "media");

const EXT_BY_MIME: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/svg+xml": "svg",
  "image/avif": "avif",
  "image/bmp": "bmp",
};

export function extForMime(mimeType: string): string {
  return EXT_BY_MIME[mimeType] ?? "bin";
}

/** Resolve a storage key to an absolute path, refusing anything that escapes the root. */
function resolveKey(storageKey: string): string {
  const full = path.resolve(MEDIA_ROOT, storageKey);
  const rootWithSep = MEDIA_ROOT.endsWith(path.sep) ? MEDIA_ROOT : MEDIA_ROOT + path.sep;
  if (full !== MEDIA_ROOT && !full.startsWith(rootWithSep)) {
    throw new Error("Invalid storage key.");
  }
  return full;
}

/** Writes bytes to a fresh `<userId>/<uuid>.<ext>` file and returns its storage key. */
export async function saveMediaFile(
  userId: string,
  bytes: Buffer,
  mimeType: string,
): Promise<string> {
  const storageKey = `${userId}/${randomUUID()}.${extForMime(mimeType)}`;
  const full = resolveKey(storageKey);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, bytes);
  return storageKey;
}

export async function readMediaFile(storageKey: string): Promise<Buffer> {
  return fs.readFile(resolveKey(storageKey));
}

export async function deleteMediaFile(storageKey: string): Promise<void> {
  await fs.rm(resolveKey(storageKey), { force: true });
}
