import { randomUUID } from "crypto";
import {
  DeleteObjectCommand,
  GetObjectCommand,
  NoSuchKey,
  PutObjectCommand,
} from "@aws-sdk/client-s3";

import { getR2 } from "@/lib/r2";

// Cloudflare R2 backend for the universal media system. Objects live in a PRIVATE
// bucket and are only ever served through the auth-scoped GET /api/media/[id]
// route — never as public assets. The storage key is `<userId>/<uuid>.<ext>`,
// generated by us, so nothing user-supplied ever reaches the object key.

const EXT_BY_MIME: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/gif": "gif",
  "image/svg+xml": "svg",
  "image/avif": "avif",
  "image/bmp": "bmp",
};

export function extForMime(mimeType: string): string {
  return EXT_BY_MIME[mimeType] ?? "bin";
}

/**
 * Guards against a malformed key reaching R2 (keys are ours, but this is
 * cheap). Release-gate finding: this previously required the FIRST segment
 * (the userId) to be hex-only (`[0-9a-f-]+`), but `saveMediaFile` builds keys
 * as `<userId>/<uuid>.<ext>` where `userId` is a Prisma `cuid()` — lowercase
 * alphanumeric, NOT restricted to hex (e.g. "cmty4b7m900003zsb6qsyhmj5"
 * contains 't', 'y', 'z', 's', 'j', 'm', none of which are hex digits). That
 * meant this check threw a plain `Error` (never `MediaNotFoundError`) for
 * EVERY real asset — `readMediaFile` always failed, and GET /api/media/[id]
 * always returned 502 — live-confirmed: the object itself was always a
 * perfectly valid, uncorrupted file when read directly from R2 bypassing
 * this check. Only the second segment (`randomUUID()`) is an actual hex
 * UUID; the first is validated against the real cuid alphabet instead. */
function assertValidKey(storageKey: string): void {
  if (!/^[a-z0-9]+\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.[a-z0-9]+$/i.test(storageKey)) {
    throw new Error("Invalid storage key.");
  }
}

/** Uploads bytes under a fresh `<userId>/<uuid>.<ext>` key and returns that key. */
export async function saveMediaFile(
  userId: string,
  bytes: Buffer,
  mimeType: string,
): Promise<string> {
  const storageKey = `${userId}/${randomUUID()}.${extForMime(mimeType)}`;
  const { client, bucket } = getR2();
  await client.send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: storageKey,
      Body: bytes,
      ContentType: mimeType,
    }),
  );
  return storageKey;
}

export async function readMediaFile(storageKey: string): Promise<Buffer> {
  assertValidKey(storageKey);
  const { client, bucket } = getR2();
  try {
    const res = await client.send(
      new GetObjectCommand({ Bucket: bucket, Key: storageKey }),
    );
    if (!res.Body) throw new Error("Empty object body.");
    const bytes = await res.Body.transformToByteArray();
    return Buffer.from(bytes);
  } catch (e) {
    if (e instanceof NoSuchKey) {
      const err = new Error("Media object not found.");
      err.name = "MediaNotFoundError";
      throw err;
    }
    throw e;
  }
}

export async function deleteMediaFile(storageKey: string): Promise<void> {
  assertValidKey(storageKey);
  const { client, bucket } = getR2();
  await client.send(new DeleteObjectCommand({ Bucket: bucket, Key: storageKey }));
}
