-- SOT P9: drop the global Asset / TradingSession / ChecklistItemDefinition tables and
-- the Trade FKs, making assetSymbol / selectedSession / selected* the source of truth.
-- Backfill FIRST (while the old tables still exist) so no historical trade loses data.

-- Backfill assetSymbol from the linked Asset (assetSymbol becomes NOT NULL below).
UPDATE "Trade" t
SET "assetSymbol" = a."symbol"
FROM "Asset" a
WHERE t."assetId" = a."id" AND t."assetSymbol" IS NULL;

-- Backfill selectedSession from the linked TradingSession.
UPDATE "Trade" t
SET "selectedSession" = s."name"
FROM "TradingSession" s
WHERE t."sessionId" = s."id" AND t."selectedSession" IS NULL;

-- Backfill selectedConfluences (by name) from the legacy checklist join, for
-- pre-SOT trades only (SOT trades already carry a — possibly empty — array).
UPDATE "Trade" t
SET "selectedConfluences" = sub.arr
FROM (
  SELECT tcs."tradeId", to_jsonb(array_agg(cid."label" ORDER BY cid."label")) AS arr
  FROM "TradeChecklistSelection" tcs
  JOIN "ChecklistItemDefinition" cid ON cid."id" = tcs."checklistItemId"
  WHERE cid."type" = 'CONFLUENCE'
  GROUP BY tcs."tradeId"
) sub
WHERE t."id" = sub."tradeId" AND t."selectedConfluences" IS NULL;

-- Backfill selectedExecution (by name) from the legacy checklist join.
UPDATE "Trade" t
SET "selectedExecution" = sub.arr
FROM (
  SELECT tcs."tradeId", to_jsonb(array_agg(cid."label" ORDER BY cid."label")) AS arr
  FROM "TradeChecklistSelection" tcs
  JOIN "ChecklistItemDefinition" cid ON cid."id" = tcs."checklistItemId"
  WHERE cid."type" = 'EXECUTION_CONFIRMATION'
  GROUP BY tcs."tradeId"
) sub
WHERE t."id" = sub."tradeId" AND t."selectedExecution" IS NULL;

-- Safety net: any trade still missing a market symbol (shouldn't happen — assetId
-- was NOT NULL) gets a placeholder so the NOT NULL constraint below can be applied.
UPDATE "Trade" SET "assetSymbol" = 'UNKNOWN' WHERE "assetSymbol" IS NULL;

-- ---------------------------------------------------------------------------
-- Structural drops (generated by prisma migrate diff).
-- ---------------------------------------------------------------------------

-- DropForeignKey
ALTER TABLE "Asset" DROP CONSTRAINT "Asset_userId_fkey";

-- DropForeignKey
ALTER TABLE "ChecklistItemDefinition" DROP CONSTRAINT "ChecklistItemDefinition_userId_fkey";

-- DropForeignKey
ALTER TABLE "Trade" DROP CONSTRAINT "Trade_assetId_fkey";

-- DropForeignKey
ALTER TABLE "Trade" DROP CONSTRAINT "Trade_sessionId_fkey";

-- DropForeignKey
ALTER TABLE "TradeChecklistSelection" DROP CONSTRAINT "TradeChecklistSelection_checklistItemId_fkey";

-- DropForeignKey
ALTER TABLE "TradeChecklistSelection" DROP CONSTRAINT "TradeChecklistSelection_tradeId_fkey";

-- DropForeignKey
ALTER TABLE "TradingSession" DROP CONSTRAINT "TradingSession_userId_fkey";

-- AlterTable
ALTER TABLE "Trade" DROP COLUMN "assetId",
DROP COLUMN "sessionId",
ALTER COLUMN "assetSymbol" SET NOT NULL;

-- AlterTable
ALTER TABLE "TradingDay" DROP COLUMN "watchlistFocus";

-- DropTable
DROP TABLE "Asset";

-- DropTable
DROP TABLE "ChecklistItemDefinition";

-- DropTable
DROP TABLE "TradeChecklistSelection";

-- DropTable
DROP TABLE "TradingSession";

-- DropEnum
DROP TYPE "ChecklistType";
